version: 2
jobs:
  test:
    docker:
        # specify the version
        - image: circleci/golang:1.14
    steps:
        - checkout
        # Run tests
        - run: go test -v
  deploy:
    docker:
        - image: flyio/flyctl:v0.0.137
    steps:
        - run: 
            name: Deploy Application to Fly
            command: flyctl deploy



workflows:
    version: 2
    test-and-deploy:
        jobs:
            - test
            - deploy:
                requires:
                    - test
                filters:
                    branches:
                        only: main
