version: 2
jobs:
  test:
    docker:
        # specify the version
        - image: circleci/golang:1.14
    steps:
        - checkout
        # Run tests
        - run: go test -v
  deploy:
    docker:
        - image: alpine:3.12
    steps:
        - run: 
            name: Deploy Application to Fly
            command: scipts/deploy.sh


workflows:
    version: 2
    test-and-deploy:
        jobs:
            - test
            - deploy:
                requires:
                    - test
                context: flygreeting
                filters:
                    branches:
                        only: main
